### ISSUE TITLE
Using it with React

### ISSUE THREAD

**Issue by konekoya** [GeekJosh/tinymce-emoji#1]
Hi Josh,

I'm trying to integrate this plugin into my React App.

My component looks like this:

```javascript

const Editor = ({
  content,
  handleChange,
}) => {
  return (
    <div>
        <TinyMCE
          content={content}
          config={{
            plugins: '',
            toolbar: `undo redo`,
            external_plugins: {
              emoji: require('tinymce-emoji'),
            },
          }}
          onChange={handleChange}
        />
    </div>
  );
};
``` 
My problem is how do you show the emoji dropdown / menu on the toolbar?
I've tried to put `emoji` in the `toolbar` prop, but got `Uncaught SyntaxError: Unexpected token import`.

Thank you!

**Comment by GeekJosh** [comment]
It seems plugin loading doesn't work quite like it's described in the tinymce docs (no surprise there); I'll do some more testing this evening and find a more reliable method to import the plugin

**Comment by konekoya** [comment]
@GeekJosh 
Thanks, Josh! Yeah, it's still not working after I changed the `emoji` to `tinymceEmoji`.
I'm not quite sure about why, but I think you may need to use commonJS instead of ES6 module for you package?

**Comment by GeekJosh** [comment]
@konekoya thanks for being patient, the issue should now be resolved, please pull down the latest version of the package then install the plugin like so:

```JavaScript
import 'tinymce-emoji'

tinymce.init({
    plugins: [
        'tinymceEmoji'
    ],
    toolbar: 'tinymceEmoji'
})
```
Thank you for your patience, and please do let me know if you have any more issues - this is the first package I've published via NPM so I have some learning to do!

**Comment by konekoya** [comment]
Hi Josh,
Sorry for the late reply. I'm kind of busy these days and still, I cannot figure out how to integrate it into my React codebase. I'll give it another shot later. Thanks for your hard work! And the quick response.
